---
# tasks file for ansible-role-netbird
- name: Add some required packages
  package:
    name:
      - ca-certificates
      - curl
      - gnupg

- name: Download the public key for Wiretrustee
  get_url:
    url: https://pkgs.wiretrustee.com/debian/public.key
    dest: /usr/local/src/netbird-wiretrustee-public.key
    owner: root
    group: root
    mode: 0755

- name: Dearmor the public key into the new binary format
  shell:
   cmd: "cat /usr/local/src/netbird-wiretrustee-public.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/wiretrustee.gpg"
   creates: /etc/apt/trusted.gpg.d/wiretrustee.gpg

- name: Install apt repository
  apt_repository:
    repo: deb https://pkgs.wiretrustee.com/debian stable main
    state: present
    filename: netbird-wiretrustee

- name: Update apt cache
  apt:
    update_cache: true

- name: Install netbird
  apt:
    name: netbird
    state: present

- name: Ensure netbird is up
  shell:
    cmd: 'netbird status | grep "Daemon status"'
  register: netbird_status
  changed_when: false
  when: netbird_register is true

- name: Register Netbird peer
  shell:
    cmd: 'netbird up --setup-key {{ netbird_setup_key }}'
  when: "netbird_register is true and 'NeedsLogin' in netbird_status.stdout"